In [29]:
import numpy as np
import matplotlib.pyplot as plt

a = 1.0
b = 3.0
c = 1.0
d = 5.0
r = 0.006
s = 5.2
x_rest = -1.56

I=0
p=3.86
#q=4.090
q=4.236

print("p =", p)
print("q =", q)

# compute u and v
u3=(-q/2)+np.sqrt((((q**2)/4))+((p**3)/27))
v3=(-q/2)-np.sqrt((((q**2)/4))+((p**3)/27))

u=np.cbrt(u3)
v=np.cbrt(v3)
print("u =",u)
print("v =",v)
root=u+v
print("root =",root)

# Fixed point values
x_e = root-2/3
y_e = 1-(5*(x_e**2))
z_e = 5.2*(x_e+1.56)

print("xe =",x_e)
print("ye =",y_e)
print("ze =",z_e)
f=((-3*(x_e**2)) + 2*b*x_e)
print(f)
k=(-2*(d*x_e))

# Function to compute Jacobian matrix
J = np.array([  [f, 1., -1.], 
               [k, -1., 0.],
               [0.0312, 0., -0.006]])
print(J)
  


# Compute eigenvalues 
eigenvalues,eigenvectors = np.linalg.eig(J)
print(eigenvalues)
   
trace=np.trace(J)
print("trace =", trace)
det=np.linalg.det(J)
print("det =", det)



p = 3.86
q = 4.236
u = 0.7686644274310563
v = -1.6738990653786583
root = -0.905234637947602
xe = -1.5719013046142685
ye = -11.354368557240196
ze = -0.06188678399419576
-16.84402896202973
[[-1.6844029e+01  1.0000000e+00 -1.0000000e+00]
 [ 1.5719013e+01 -1.0000000e+00  0.0000000e+00]
 [ 3.1200000e-02  0.0000000e+00 -6.0000000e-03]]
[-17.77909478+0.j          -0.03546709+0.02960777j
  -0.03546709-0.02960777j]
trace = -17.85002896202973
det = -0.03795009549532226
